/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ping.service;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("Begin ping-service initialization...");
        System.out.println("End ping-service initialization...");
    }
}
