/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ping.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ping.service.app.server.ServerJetty;

public class App {
    private static final Logger log = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) throws Exception {
        log.info("Begin ping-service initialization...");
        new ServerJetty().start();
        log.info("End ping-service initialization...");
    }
}
